// packages/components-vue/src/Alert.vue
<script setup>
import "./styles.css";
import Icon from "./Icon.js";
import { ref } from "vue";
const props = defineProps({ message: { type: String, default: "系统将在今晚自动完成更新。" }, action: { type: String, default: "查看详情" }, tone: { type: String, default: "info" } });
const emit = defineEmits(["action", "close"]); const visible = ref(true);
const toneIcons = { info: "status/info", success: "status/success", warning: "status/warning", danger: "status/danger", neutral: "status/neutral" };
</script>
<template><div v-if="visible" class="tui-component tui-alert" :class="`tui-alert--${props.tone}`" data-component="alert" data-logical-component="Alert/Default" :data-variant="props.tone" data-state="default" data-framework="vue" :role="props.tone === 'warning' || props.tone === 'danger' ? 'alert' : 'status'"><span class="tui-alert__icon"><Icon :name="toneIcons[props.tone] ?? toneIcons.info" :size="20" /></span><span class="tui-alert__message" data-slot="content" data-typography-role="subtitle-s">{{ props.message }}</span><span class="tui-alert__actions" data-slot="actions"><button class="tui-button tui-button--ghost tui-alert__action" data-slot="action" type="button" data-variant="ghost" data-size="small" data-typography-role="body-m" @click="emit('action')">{{ props.action }}</button><button class="tui-icon-button" data-slot="close" type="button" aria-label="关闭" @click="visible = false; emit('close')"><Icon name="action/close" :size="20" /></button></span></div></template>

// packages/components-react/src/generated/Alert.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Alert({ label = "系统将在今晚自动完成更新。", description = "查看详情", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "查看详情";
  return (
    <div className="tui-generated tui-generated--feedback" data-component="alert" data-logical-component="Alert/Default" data-variant="info" data-state="default" data-framework="react" role="status"><Icon name="status/info" /><span data-slot="label" data-typography-role="subtitle-s">系统将在今晚自动完成更新。</span><span data-slot="content" data-typography-role="body-l"><span>查看详情</span></span><button className="tui-icon-button" type="button" aria-label="关闭"><Icon name="action/close" /></button></div>
  );
}

export default Alert;
