// packages/components-vue/src/generated/Avatar.vue
<script setup>
import { ref } from "vue";
const props = defineProps({ label: { type: String, default: "H" }, description: { type: String, default: "HarmonyOS" }, state: { type: String, default: "default" } });
const open = ref(false);
</script>

<template>
  <div class="tui-generated tui-generated--avatar" data-component="avatar" data-logical-component="Avatar/Default" data-variant="default" data-state="default" data-framework="vue" data-slot="content">H</div>
</template>

// packages/components-react/src/generated/Avatar.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Avatar({ label = "H", description = "HarmonyOS", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "HarmonyOS";
  return (
    <div className="tui-generated tui-generated--avatar" data-component="avatar" data-logical-component="Avatar/Default" data-variant="default" data-state="default" data-framework="react" data-slot="content">H</div>
  );
}

export default Avatar;
