// packages/components-vue/src/generated/Collapsible.vue
<script setup>
import { ref } from "vue";
const props = defineProps({ label: { type: String, default: "更多信息" }, description: { type: String, default: "点击展开详情" }, state: { type: String, default: "default" } });
const open = ref(false);
</script>

<template>
  <div class="tui-generated tui-generated--disclosure" data-component="collapsible" data-logical-component="Collapsible/Default" data-variant="default" data-state="default" data-framework="vue">
    <button class="tui-generated__disclosure" type="button" :aria-expanded="open" aria-controls="collapsible-content" @click="open = !open" data-typography-role="body-l">
      <span data-slot="label" data-typography-role="body-l">更多信息</span>
      <svg class="tui-icon tui-icon--regular" viewBox="0 0 24 24" width="20" height="20" data-icon-alias="navigation/chevron-down" data-icon-size="20" data-icon-kind="regular" aria-hidden="true"><path d="m6 9 6 6 6-6" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></svg>
    </button>
    <div class="tui-generated__disclosure-content" id="collapsible-content" data-slot="content" :hidden="!open" data-typography-role="body-l">点击展开详情</div>
  </div>
</template>

// packages/components-react/src/generated/Collapsible.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Collapsible({ label = "更多信息", description = "点击展开详情", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "点击展开详情";
  return (
    <div className="tui-generated tui-generated--disclosure" data-component="collapsible" data-logical-component="Collapsible/Default" data-variant="default" data-state="default" data-framework="react" {...props}>
      <button className="tui-generated__disclosure" type="button" aria-expanded={open} aria-controls="collapsible-content" onClick={() => setOpen(!open)} data-typography-role="body-l">
        <span data-slot="label" data-typography-role="body-l">{label}</span>
        <Icon name="navigation/chevron-down" size={20} />
      </button>
      <div className="tui-generated__disclosure-content" id="collapsible-content" data-slot="content" hidden={!open} data-typography-role="body-l">{content}</div>
    </div>
  );
}

export default Collapsible;
