// packages/components-vue/src/Field.vue
<script setup>
import "./styles.css";
import { computed, ref } from "vue";
const props = defineProps({ modelValue: String, label: { type: String, default: "项目名称" }, placeholder: { type: String, default: "请输入内容" }, help: { type: String, default: "" }, disabled: Boolean, error: Boolean, state: { type: String, default: "default" }, surface: { type: String, default: "white" } });
const emit = defineEmits(["update:modelValue"]);
const focused = ref(false);
const resolvedState = computed(() => props.disabled ? "disabled" : props.state !== "default" ? props.state : props.error ? "error" : focused.value ? "focus" : "default");
</script>
<template>
  <label class="tui-component tui-field" data-component="field" data-logical-component="Field/Default" data-variant="default" :data-state="resolvedState" :data-surface="props.surface" data-framework="vue"><span data-slot="label" data-typography-role="body-m">{{ props.label }}</span><span class="tui-field__control"><input data-slot="value" data-typography-role="body-l" :value="props.modelValue" :placeholder="props.placeholder" :disabled="props.disabled" :aria-invalid="props.error || props.state === 'error' ? 'true' : undefined" @focus="focused = true" @blur="focused = false" @input="emit('update:modelValue', $event.target.value)" /></span><span v-if="props.help" data-slot="help" data-typography-role="caption-l">{{ props.help }}</span></label>
</template>

// packages/components-react/src/generated/Field.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Field({ label = "项目名称", description = "客户端设计系统", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "客户端设计系统";
  return (
    <label className="tui-generated tui-generated--field" data-component="field" data-logical-component="Field/Default" data-variant="default" data-state="default" data-framework="react"><span data-slot="label" data-typography-role="body-m"><span className="tui-generated__label" data-typography-role="body-m">项目名称</span></span><span className="tui-generated__control"><span data-slot="leading"><Icon name="field/search" /></span><input data-slot="value" data-typography-role="body-l" type="text"  defaultValue="客户端设计系统" /><span data-slot="trailing" data-typography-role="body-m"><Icon name="navigation/chevron-down" /></span></span><span data-slot="help" data-typography-role="caption-l"><small data-typography-role="caption-l">客户端设计系统</small></span></label>
  );
}

export default Field;
