// packages/components-vue/src/generated/Kbd.vue
<script setup>
import { ref } from "vue";
const props = defineProps({ label: { type: String, default: "快捷键" }, description: { type: String, default: "⌘ K" }, state: { type: String, default: "default" } });
const open = ref(false);
</script>

<template>
  <span class="tui-generated tui-generated--inline" data-component="kbd" data-logical-component="Kbd/Default" data-variant="default" data-state="default" data-framework="vue" data-slot="label">⌘ K</span>
</template>

// packages/components-react/src/generated/Kbd.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Kbd({ label = "快捷键", description = "⌘ K", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "⌘ K";
  return (
    <span className="tui-generated tui-generated--inline" data-component="kbd" data-logical-component="Kbd/Default" data-variant="default" data-state="default" data-framework="react" data-slot="label">⌘ K</span>
  );
}

export default Kbd;
