// packages/components-vue/src/NativeSelect.vue
<script setup>
import "./styles.css";
import Icon from "./Icon.js";
const props = defineProps({ modelValue: String, label: { type: String, default: "视图" }, options: { type: Array, default: () => ["列表视图", "网格视图", "紧凑视图"] }, disabled: Boolean, state: { type: String, default: "default" }, surface: { type: String, default: "white" } });
const emit = defineEmits(["update:modelValue", "change"]);
</script>
<template>
  <label class="tui-component tui-native-select" data-component="native-select" data-logical-component="Native Select/Default" data-variant="default" :data-state="props.disabled ? 'disabled' : props.state" :data-surface="props.surface" data-framework="vue"><span data-slot="label" data-typography-role="body-m">{{ props.label }}</span><span class="tui-native-select__control"><select data-slot="value" data-typography-role="body-l" :value="props.modelValue" :disabled="props.disabled" @change="emit('update:modelValue', $event.target.value); emit('change', $event.target.value)"><option v-for="option in props.options" :key="option" :value="option">{{ option }}</option></select><Icon name="navigation/chevron-down" :size="16" /></span></label>
</template>

// packages/components-react/src/generated/NativeSelect.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function NativeSelect({ label = "视图", description = "列表视图", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "列表视图";
  return (
    <div className="tui-generated tui-generated--menu" data-component="native-select" data-logical-component="Native Select/Default" data-variant="default" data-state="default" data-framework="react"><span data-slot="label" data-typography-role="body-m"><span data-typography-role="body-m">视图</span></span><button className="tui-generated__control" type="button" aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen(!open)}><span data-slot="leading"><Icon name="navigation/chevron-down" /></span><span data-slot="value" data-typography-role="body-m">列表视图</span><Icon name="navigation/chevron-down" /></button><div className="tui-generated__menu" role="menu" data-slot="content" hidden={!open}><button type="button" role="menuitem" data-typography-role="body-l">列表视图</button><button type="button" role="menuitem" data-typography-role="body-l">全部项目</button><button type="button" role="menuitem" data-typography-role="body-l">最近访问</button></div><span data-slot="help" data-typography-role="body-s"><small data-typography-role="body-s">选择一个选项</small></span></div>
  );
}

export default NativeSelect;
