// packages/components-vue/src/RadioGroup.vue
<script setup>
import "./styles.css";
import { computed, ref } from "vue";
const props = defineProps({ modelValue: String, label: { type: String, default: "通知方式" }, options: { type: Array, default: () => ["邮件", "站内消息"] } });
const emit = defineEmits(["update:modelValue", "change"]); const internal = ref(props.options[0]);
const selected = computed(() => props.modelValue === undefined ? internal.value : props.modelValue);
const change = (event) => { if (props.modelValue === undefined) internal.value = event.target.value; emit("update:modelValue", event.target.value); emit("change", event.target.value); };
</script>
<template><fieldset class="tui-component tui-choice tui-radio-group" data-component="radio-group" data-logical-component="Radio Group/Default" data-variant="default" data-state="default" data-framework="vue"><legend data-slot="label" data-typography-role="body-m">{{ props.label }}</legend><label v-for="option in props.options" :key="option"><input type="radio" name="runtime-radio" :value="option" :checked="selected === option" @change="change" /><span class="tui-radio__indicator" aria-hidden="true"></span><span data-typography-role="body-m">{{ option }}</span></label></fieldset></template>

// packages/components-react/src/generated/RadioGroup.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function RadioGroup({ label = "通知方式", description = "邮件 / 站内消息", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "邮件 / 站内消息";
  return (
    <label className="tui-generated tui-generated--choice" data-component="radio-group" data-logical-component="Radio Group/Default" data-variant="default" data-state="default" data-framework="react"><input type="radio"  defaultChecked /><span data-slot="label" data-typography-role="body-l">通知方式</span><span data-slot="description" data-typography-role="body-m">邮件 / 站内消息</span></label>
  );
}

export default RadioGroup;
