// packages/components-vue/src/Select.vue
<script setup>
import "./styles.css";
import { computed, nextTick, ref } from "vue";
import Icon from "./Icon.js";
const props = defineProps({ modelValue: String, label: { type: String, default: "状态" }, options: { type: Array, default: () => ["进行中", "已完成", "已归档"] }, disabled: Boolean, state: { type: String, default: "default" }, surface: { type: String, default: "white" } });
const emit = defineEmits(["update:modelValue", "change"]);
const open = ref(false);
const trigger = ref(null);
const current = ref(props.modelValue ?? props.options[0]);
const selected = computed(() => props.modelValue === undefined ? current.value : props.modelValue);
const choose = (option) => { if (props.modelValue === undefined) current.value = option; emit("update:modelValue", option); emit("change", option); open.value = false; nextTick(() => trigger.value?.focus()); };
const onKeyDown = (event) => { if (props.disabled) return; const index = Math.max(0, props.options.indexOf(selected.value)); if (event.key === "Escape") { event.preventDefault(); open.value = false; trigger.value?.focus(); } else if (event.key === "Enter" || event.key === " ") { event.preventDefault(); open.value = !open.value; } else if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); if (!open.value) open.value = true; else choose(props.options[(index + (event.key === "ArrowDown" ? 1 : props.options.length - 1)) % props.options.length]); } };
</script>
<template>
  <div class="tui-component tui-select" data-component="select" data-logical-component="Select/Default" data-variant="default" :data-state="props.disabled ? 'disabled' : props.state" :data-surface="props.surface" data-framework="vue"><span data-slot="label" data-typography-role="body-m">{{ props.label }}</span><button ref="trigger" class="tui-select__trigger" type="button" role="button" aria-haspopup="listbox" :aria-expanded="open" aria-controls="select-options" :disabled="props.disabled" @click="open = !open" @keydown="onKeyDown"><span data-slot="value" data-typography-role="body-m">{{ selected }}</span><Icon name="navigation/chevron-down" :size="16" /></button><div id="select-options" class="tui-select__menu" role="listbox" :hidden="!open" :aria-label="props.label"><button v-for="option in props.options" :key="option" type="button" role="option" :aria-selected="option === selected" data-typography-role="body-l" @click="choose(option)">{{ option }}</button></div></div>
</template>

// packages/components-react/src/generated/Select.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Select({ label = "状态", description = "进行中", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "进行中";
  return (
    <div className="tui-generated tui-generated--menu" data-component="select" data-logical-component="Select/Default" data-variant="default" data-state="default" data-framework="react"><span data-slot="label" data-typography-role="body-m"><span data-typography-role="body-m">状态</span></span><button className="tui-generated__control" type="button" aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen(!open)}><span data-slot="leading"><Icon name="navigation/chevron-down" /></span><span data-slot="value" data-typography-role="body-m">进行中</span><Icon name="navigation/chevron-down" /></button><div className="tui-generated__menu" role="menu" data-slot="content" hidden={!open}><button type="button" role="menuitem" data-typography-role="body-l">进行中</button><button type="button" role="menuitem" data-typography-role="body-l">全部项目</button><button type="button" role="menuitem" data-typography-role="body-l">最近访问</button></div><span data-slot="help" data-typography-role="body-s"><small data-typography-role="body-s">选择一个选项</small></span></div>
  );
}

export default Select;
