// packages/components-vue/src/Textarea.vue
<script setup>
import "./styles.css";
import { computed, ref } from "vue";
const props = defineProps({ modelValue: String, label: { type: String, default: "项目说明" }, placeholder: { type: String, default: "请输入内容" }, help: { type: String, default: "" }, disabled: Boolean, error: Boolean, state: { type: String, default: "default" }, surface: { type: String, default: "white" } });
const emit = defineEmits(["update:modelValue"]);
const focused = ref(false);
const resolvedState = computed(() => props.disabled ? "disabled" : props.state !== "default" ? props.state : props.error ? "error" : focused.value ? "focus" : "default");
</script>
<template>
  <label class="tui-component tui-textarea" data-component="textarea" data-logical-component="Textarea/Default" data-variant="default" :data-state="resolvedState" :data-surface="props.surface" data-framework="vue"><span data-slot="label" data-typography-role="body-m">{{ props.label }}</span><textarea data-slot="value" data-typography-role="body-l" :value="props.modelValue" :placeholder="props.placeholder" :disabled="props.disabled" :aria-invalid="props.error || props.state === 'error' ? 'true' : undefined" @focus="focused = true" @blur="focused = false" @input="emit('update:modelValue', $event.target.value)"></textarea><span v-if="props.help" data-slot="help" data-typography-role="caption-l">{{ props.help }}</span></label>
</template>

// packages/components-react/src/generated/Textarea.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Textarea({ label = "项目说明", description = "统一 HarmonyOS PC 客户端中的布局、组件与交互规则。", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "统一 HarmonyOS PC 客户端中的布局、组件与交互规则。";
  return (
    <label className="tui-generated tui-generated--field" data-component="textarea" data-logical-component="Textarea/Default" data-variant="default" data-state="default" data-framework="react"><span data-slot="label" data-typography-role="body-l"><span className="tui-generated__label" data-typography-role="body-m">项目说明</span></span><span className="tui-generated__control"><span data-slot="leading"><Icon name="field/search" /></span><textarea data-slot="value" data-typography-role="body-l" rows="3" defaultValue="统一 HarmonyOS PC 客户端中的布局、组件与交互规则。" /><span data-slot="trailing" data-typography-role="body-m"><Icon name="navigation/chevron-down" /></span></span><span data-slot="help" data-typography-role="caption-l"><small data-typography-role="caption-l">统一 HarmonyOS PC 客户端中的布局、组件与交互规则。</small></span></label>
  );
}

export default Textarea;
