// packages/components-vue/src/Chips.vue
<script setup>
import "./styles.css";
import { computed, useSlots } from "vue";
import Icon from "./Icon.js";

const props = defineProps({
  label: { type: String, default: "操作块" },
  icon: { type: String, default: "action/mark-important" },
  closable: { type: Boolean, default: true },
  disabled: { type: Boolean, default: false },
  state: { type: String, default: "default" }
});
const emit = defineEmits(["close"]);
const slots = useSlots();
const resolvedState = computed(() => props.disabled ? "disabled" : props.state);
const variant = computed(() => `${props.icon || Boolean(slots.leading) ? "with-icon" : "text-only"}${props.closable ? "-closable" : ""}`);
</script>

<template>
  <span class="tui-component tui-chip" data-component="chips" data-renderer-key="chips" data-logical-component="Chips/Default" :data-variant="variant" :data-state="resolvedState" data-framework="vue" :data-close="closable ? undefined : 'false'" :aria-disabled="disabled || undefined">
    <span v-if="icon || $slots.leading" class="tui-chip__leading" data-slot="leading"><slot name="leading"><Icon :name="icon" :size="16" /></slot></span>
    <span class="tui-chip__label" data-slot="label" data-typography-role="body-m"><slot name="label">{{ label }}</slot></span>
    <slot name="close"><button v-if="closable" class="tui-chip__close" data-slot="close" type="button" :aria-label="`移除 ${label}`" :disabled="disabled" @click="emit('close')"><Icon name="action/close" :size="16" /></button></slot>
  </span>
</template>

// packages/components-react/src/Chips.jsx
import React from "react";
import { Icon, contract } from "./shared.jsx";
import "./styles.css";

export function Chips({ label = "操作块", icon = "action/mark-important", leading, closable = true, disabled = false, state = "default", onClose, ...props }) {
  const resolvedState = disabled ? "disabled" : state;
  const variant = `${icon || leading ? "with-icon" : "text-only"}${closable ? "-closable" : ""}`;
  return <span className="tui-component tui-chip" {...contract("chips", "Chips/Default", variant, resolvedState, { "data-close": closable ? undefined : "false", "aria-disabled": disabled || undefined })} {...props}>
    {(icon || leading) && <span className="tui-chip__leading" data-slot="leading">{leading ?? <Icon name={icon} size={16} />}</span>}
    <span className="tui-chip__label" data-slot="label" data-typography-role="body-m">{label}</span>
    {closable && <button className="tui-chip__close" data-slot="close" type="button" aria-label={`移除 ${label}`} disabled={disabled} onClick={onClose}><Icon name="action/close" size={16} /></button>}
  </span>;
}
