// packages/components-vue/src/LegacyCatalog.vue
<script setup>
import "./styles.css";
import { legacyCatalogMarkup } from "../../component-contracts/src/legacy-catalog.js";
</script>

<template>
  <div class="tui-legacy-catalog" data-component="legacy-catalog" data-logical-component="Catalog/Legacy Skill Baseline" data-variant="canonical" data-state="default" data-framework="vue" v-html="legacyCatalogMarkup"></div>
</template>

// packages/components-react/src/LegacyCatalog.jsx
import "./styles.css";
import { legacyCatalogMarkup, legacyCatalogComponentNames } from "../../component-contracts/src/legacy-catalog.js";

export { legacyCatalogComponentNames };

export function LegacyCatalog({ className = "", ...props }) {
  return <div className={`tui-legacy-catalog${className ? ` ${className}` : ""}`} data-component="legacy-catalog" data-logical-component="Catalog/Legacy Skill Baseline" data-variant="canonical" data-state="default" data-framework="react" dangerouslySetInnerHTML={{ __html: legacyCatalogMarkup }} {...props} />;
}
