// packages/components-react/src/generated/Alert.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Alert({ label = "系统将在今晚自动完成更新。", description = "查看详情", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "查看详情";
  return (
    <div className="tui-generated tui-generated--feedback" data-component="alert" data-logical-component="Alert/Default" data-variant="info" data-state="default" data-framework="react" role="status"><Icon name="status/info" /><span data-slot="label" data-typography-role="subtitle-s">系统将在今晚自动完成更新。</span><span data-slot="content" data-typography-role="body-l"><span>查看详情</span></span><button className="tui-icon-button" type="button" aria-label="关闭"><Icon name="action/close" /></button></div>
  );
}

export default Alert;

// packages/components-vue/src/generated/Alert.vue
<script setup>
import { ref } from "vue";
const props = defineProps({ label: { type: String, default: "系统将在今晚自动完成更新。" }, description: { type: String, default: "查看详情" }, state: { type: String, default: "default" } });
const open = ref(false);
</script>

<template>
  <div class="tui-generated tui-generated--feedback" data-component="alert" data-logical-component="Alert/Default" data-variant="info" data-state="default" data-framework="vue" role="status"><svg class="tui-icon tui-icon--regular" viewBox="0 0 24 24" width="20" height="20" data-icon-alias="status/info" data-icon-size="20" data-icon-kind="regular" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 16v-4" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 8h.01" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></svg><span data-slot="label" data-typography-role="subtitle-s">系统将在今晚自动完成更新。</span><span data-slot="content" data-typography-role="body-l"><span>查看详情</span></span><button class="tui-icon-button" type="button" aria-label="关闭"><svg class="tui-icon tui-icon--regular" viewBox="0 0 24 24" width="20" height="20" data-icon-alias="action/close" data-icon-size="20" data-icon-kind="regular" aria-hidden="true"><path d="M18 6 6 18" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="m6 6 12 12" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div>
</template>
