// packages/components-react/src/generated/Attachment.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Attachment({ label = "项目说明.pdf", description = "2.4 MB · 已上传", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "2.4 MB · 已上传";
  return (
    <article className="tui-generated tui-generated--card" data-component="attachment" data-logical-component="Attachment/Default" data-variant="default" data-state="default" data-framework="react"><Icon name="action/download" /><div className="tui-generated__card-body"><span data-slot="content" data-typography-role="body-l"><p data-typography-role="body-l">2.4 MB · 已上传</p></span><span data-slot="description" data-typography-role="body-m"><small data-typography-role="body-m">辅助说明</small></span></div></article>
  );
}

export default Attachment;

// packages/components-vue/src/generated/Attachment.vue
<script setup>
import { ref } from "vue";
const props = defineProps({ label: { type: String, default: "项目说明.pdf" }, description: { type: String, default: "2.4 MB · 已上传" }, state: { type: String, default: "default" } });
const open = ref(false);
</script>

<template>
  <article class="tui-generated tui-generated--card" data-component="attachment" data-logical-component="Attachment/Default" data-variant="default" data-state="default" data-framework="vue"><svg class="tui-icon tui-icon--regular" viewBox="0 0 24 24" width="20" height="20" data-icon-alias="action/download" data-icon-size="20" data-icon-kind="regular" aria-hidden="true"><path d="M12 15V3" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="m7 10 5 5 5-5" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/></svg><div class="tui-generated__card-body"><span data-slot="content" data-typography-role="body-l"><p data-typography-role="body-l">2.4 MB · 已上传</p></span><span data-slot="description" data-typography-role="body-m"><small data-typography-role="body-m">辅助说明</small></span></div></article>
</template>
