// packages/components-react/src/generated/Carousel.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Carousel({ label = "内容 1 / 3", description = "项目概览", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "项目概览";
  return (
    <article className="tui-generated tui-generated--card" data-component="carousel" data-logical-component="Carousel/Default" data-variant="default" data-state="default" data-framework="react"><Icon name="navigation/chevron-down" /><div className="tui-generated__card-body"><span data-slot="content" data-typography-role="body-l"><p data-typography-role="body-l">项目概览</p></span><span data-slot="description" data-typography-role="body-m"><small data-typography-role="body-m">辅助说明</small></span></div></article>
  );
}

export default Carousel;

// packages/components-vue/src/generated/Carousel.vue
<script setup>
import { ref } from "vue";
const props = defineProps({ label: { type: String, default: "内容 1 / 3" }, description: { type: String, default: "项目概览" }, state: { type: String, default: "default" } });
const open = ref(false);
</script>

<template>
  <article class="tui-generated tui-generated--card" data-component="carousel" data-logical-component="Carousel/Default" data-variant="default" data-state="default" data-framework="vue"><svg class="tui-icon tui-icon--filled" viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" data-icon-alias="navigation/chevron-down" data-icon-size="20" data-icon-kind="filled"><path d="M12.792 15.312 18.528 9.648Q18.744 9.432 18.744 9.12Q18.744 8.808 18.528 8.568Q18.312 8.352 18 8.352Q17.688 8.352 17.448 8.568L12 13.992L6.528 8.568Q6.312 8.352 6 8.352Q5.688 8.352 5.472 8.568Q5.256 8.808 5.256 9.12Q5.256 9.432 5.472 9.648L11.208 15.312Q11.544 15.648 12 15.648Q12.456 15.648 12.792 15.312Z"/></svg><div class="tui-generated__card-body"><span data-slot="content" data-typography-role="body-l"><p data-typography-role="body-l">项目概览</p></span><span data-slot="description" data-typography-role="body-m"><small data-typography-role="body-m">辅助说明</small></span></div></article>
</template>
