// skill/fixtures/framework-component-contract/vue/CatalogModule.vue
<script setup>
import { onMounted, ref, watch } from "vue";
import { mountCatalogModule } from "../shared/catalog-module.js";
import "../shared/catalog-module.css";

const props = defineProps({ moduleId: { type: String, required: true } });
const root = ref(null);
const status = ref("loading");
async function load() {
  status.value = "loading";
  try { await mountCatalogModule(root.value, props.moduleId, "vue"); status.value = "ready"; }
  catch { status.value = "error"; }
}
onMounted(load);
watch(() => props.moduleId, load);
</script>

<template>
  <main ref="root" class="framework-catalog-module" data-component="Catalog Module" :data-logical-component="`Catalog/${moduleId}`" data-variant="gallery" :data-state="status" />
</template>

// text-to-ui/fixtures/framework-component-contract/react/CatalogModule.jsx
import { useEffect, useRef, useState } from "react";
import { mountCatalogModule } from "../shared/catalog-module.js";
import "../shared/catalog-module.css";

export function CatalogModule({ moduleId }) {
  const rootRef = useRef(null);
  const [status, setStatus] = useState("loading");
  useEffect(() => {
    let active = true;
    mountCatalogModule(rootRef.current, moduleId, "react")
      .then(() => { if (active) setStatus("ready"); })
      .catch(() => { if (active) setStatus("error"); });
    return () => { active = false; };
  }, [moduleId]);
  return <main ref={rootRef} className="framework-catalog-module" data-component="Catalog Module" data-logical-component={`Catalog/${moduleId}`} data-variant="gallery" data-state={status} />;
}
