// packages/components-react/src/generated/Badge.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Badge({ label = "进行中", description = "状态", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "状态";
  return (
    <span className="tui-generated tui-generated--inline" data-component="badge" data-logical-component="Badge/Default" data-variant="default" data-state="default" data-framework="react" data-slot="label">状态</span>
  );
}

export default Badge;

// packages/components-vue/src/Badge.vue
<script setup>
import "./styles.css";
const props = defineProps({ label: { type: String, default: "进行中" }, tone: { type: String, default: "info" }, disabled: Boolean });
</script>
<template><span class="tui-component tui-badge" :class="`tui-badge--${['info', 'success', 'warning', 'danger', 'neutral'].includes(props.tone) ? props.tone : 'info'}`" data-component="badge" data-logical-component="Badge/Default" data-variant="default" :data-state="props.disabled ? 'disabled' : 'default'" data-framework="vue" data-typography-role="caption-l">{{ props.label }}</span></template>
