// packages/components-react/src/generated/Checkbox.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Checkbox({ label = "同步到云端", description = "已选中", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "已选中";
  return (
    <label className="tui-generated tui-generated--choice" data-component="checkbox" data-logical-component="Checkbox/Default" data-variant="default" data-state="default" data-framework="react"><input type="checkbox"  defaultChecked /><span data-slot="label" data-typography-role="body-l">同步到云端</span><span data-slot="description" data-typography-role="body-m">已选中</span></label>
  );
}

export default Checkbox;

// packages/components-vue/src/Checkbox.vue
<script setup>
import "./styles.css";
import { computed, ref } from "vue";
import Icon from "./Icon.js";
const props = defineProps({ modelValue: { type: Boolean, default: undefined }, label: { type: String, default: "同步到云端" }, description: { type: String, default: "保存后自动同步" }, disabled: Boolean });
const emit = defineEmits(["update:modelValue", "change"]); const internal = ref(true);
const checked = computed(() => props.modelValue === undefined ? internal.value : props.modelValue);
const change = (event) => { if (props.modelValue === undefined) internal.value = event.target.checked; emit("update:modelValue", event.target.checked); emit("change", event.target.checked); };
</script>
<template><label class="tui-component tui-choice tui-checkbox" data-component="checkbox" data-logical-component="Checkbox/Default" data-variant="default" :data-state="props.disabled ? 'disabled' : checked ? 'selected' : 'default'" data-framework="vue"><input type="checkbox" :checked="checked" :disabled="props.disabled" @change="change" /><span class="tui-checkbox__indicator" aria-hidden="true"><Icon name="choice/check" :size="16" /></span><span data-slot="label" data-typography-role="body-m">{{ props.label }}</span><span data-slot="description" data-typography-role="body-m">{{ props.description }}</span></label></template>
