// packages/components-react/src/generated/Label.jsx
import React, { useState } from "react";
import { Icon, contract } from "../shared.jsx";
import "../styles.css";

export function Label({ label = "项目名称", description = "必填", state = "default", children, ...props }) {
  const [open, setOpen] = useState(false);
  const content = children ?? "必填";
  return (
    <section className="tui-generated tui-generated--card" data-component="label" data-logical-component="Label/Default" data-variant="default" data-state="default" data-framework="react"><span data-slot="label" data-typography-role="body-l"><span data-typography-role="title-s">项目名称</span></span><span data-slot="content" data-typography-role="body-l"><p data-typography-role="body-l">必填</p></span><span data-slot="description" data-typography-role="body-m"><small data-typography-role="body-s">辅助说明</small></span></section>
  );
}

export default Label;

// packages/components-vue/src/Label.vue
<script setup>
import "./styles.css";
const props = defineProps({ text: { type: String, default: "项目名称" }, forId: { type: String, default: "project-name" } });
</script>
<template><label class="tui-component tui-label" data-component="label" data-logical-component="Label/Default" data-variant="default" data-state="default" data-framework="vue" :for="props.forId" data-typography-role="body-m">{{ props.text }}</label></template>
